# Generated by Django 3.2.9 on 2021-11-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('en', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ru', models.CharField(max_length=30)),
                ('ua', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meeting_date', models.DateField()),
                ('mail', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('registration_date', models.DateField()),
                ('registration_language', models.CharField(max_length=30)),
            ],
        ),
    ]
